// Books Data - Central catalog of all books in the bookstore
// Master list of available genres
// Used for genre filters and add book dropdown
export const GENRE_LIST = [
    "Adventure",
    "Classic",
    "Dystopian",
    "Epic",
    "Fantasy",
    "Historical Fiction",
    "Horror",
    "Mystery",
    "Romance",
    "Science Fiction",
    "Thriller",
];
// Track the number of original books (can't be deleted)
export const ORIGINAL_BOOKS_COUNT = 9;
export const books = [
    {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Classic",
        year: 1925,
        best_seller: true,
        trending: true,
        description: "A jazz age masterpiece exploring wealth, obsession, and the American Dream through the eyes of Nick Carraway and the mysterious Jay Gatsby.",
        image: "images/Photos/book-covers/the-great-gatsby.jpg",
        link: "https://openlibrary.org/works/OL468431W/The_Great_Gatsby?edition=key%3A/books/OL35657482M",
    },
    {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        genre: "Classic",
        year: 1960,
        best_seller: true,
        trending: false,
        description: "A poignant coming-of-age story in the racially divided South, seen through the innocent eyes of Scout Finch as her father defends a Black man accused of a grave crime.",
        image: "images/Photos/book-covers/to-kill-a-mockingbird.jpg",
        link: "https://openlibrary.org/works/OL3140822W/To_Kill_a_Mockingbird?edition=key:/books/OL25228947M",
    },
    {
        title: "1984",
        author: "George Orwell",
        genre: "Dystopian",
        year: 1949,
        best_seller: false,
        trending: true,
        description: "A dystopian tale of government surveillance, propaganda, and loss of truth, where independent thought is a punishable crime and Big Brother watches all.",
        image: "images/Photos/book-covers/1984.jpg",
        link: "https://openlibrary.org/works/OL1168083W/Nineteen_Eighty-Four?edition=key:/books/OL3174961M",
    },
    {
        title: "The Adventures of Sherlock Holmes",
        author: "Arthur Conan Doyle",
        genre: "Mystery",
        year: 1892,
        best_seller: true,
        trending: false,
        description: "A brilliant detective uses keen observation and deduction to solve twelve gripping mysteries in Victorian London with his loyal partner Dr. Watson.",
        image: "images/Photos/book-covers/the-adventures-of-sherlock-holmes.jpg",
        link: "https://openlibrary.org/works/OL262421W/The_Adventures_of_Sherlock_Holmes_12_stories?edition=key:/books/OL24349267M",
    },
    {
        title: "Pride and Prejudice",
        author: "Jane Austen",
        genre: "Romance",
        year: 1813,
        best_seller: false,
        trending: true,
        description: "A timeless romantic drama about social class, misunderstandings, and the slow-burning relationship between the spirited Elizabeth Bennet and the proud Mr. Darcy.",
        image: "images/Photos/book-covers/pride-and-prejudice.jpg",
        link: "https://openlibrary.org/works/OL66554W/Pride_and_Prejudice?edition=key%3A/books/OL26394550M",
    },
    {
        title: "The Odyssey",
        author: "Homer",
        genre: "Epic",
        year: -800,
        best_seller: true,
        trending: false,
        description: "An epic journey of a cunning Greek hero returning home from war, battling mythical creatures and vengeful gods across stormy seas and strange lands.",
        image: "images/Photos/book-covers/the-odyssey.jpg",
        link: "https://openlibrary.org/works/OL26446888W/The_Odyssey?edition=key:/books/OL36188337M",
    },
    {
        title: "Frankenstein",
        author: "Mary Shelley",
        genre: "Horror",
        year: 1818,
        best_seller: true,
        trending: false,
        description: "A groundbreaking Gothic horror novel that raises timeless questions about creation, identity, and what it means to be human through the tragic tale of Victor Frankenstein and his creature.",
        image: "images/Photos/book-covers/frankenstein.jpg",
        link: "https://openlibrary.org/works/OL450063W/Frankenstein_or_The_Modern_Prometheus?edition=key:/books/OL37937792M",
    },
    {
        title: "Little Women",
        author: "Louisa May Alcott",
        genre: "Classic",
        year: 1868,
        best_seller: false,
        trending: true,
        description: "A heartwarming and sometimes heartbreaking story of four sisters growing up during the Civil War, learning about love, ambition, and family in the face of life's trials.",
        image: "images/Photos/book-covers/little-women.jpg",
        link: "https://openlibrary.org/works/OL29983W/Little_Women?edition=key:/books/OL21516677M",
    },
    {
        title: "Moby-Dick",
        author: "Herman Melville",
        genre: "Adventure",
        year: 1851,
        best_seller: false,
        trending: true,
        description: "An epic sea voyage that follows Captain Ahab’s obsessive quest to hunt the great white whale, exploring themes of obsession, fate, and man’s struggle against nature.",
        image: "images/Photos/book-covers/moby-dick.jpg",
        link: "https://openlibrary.org/works/OL102749W/Moby_Dick?edition=key%3A/books/OL37044701M",
    },
];
